spring.application.name=RentixOficial
spring.datasource.url=jdbc:mysql://localhost:3306/rentix_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Mateietare2008
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
